function f=f(x,t)
F=x(1);
Loans=x(2);
b=x(3);
fooey=x(4);
int=x(5);
int1=x(6);
foo_1=0;
tau_mathrmbar=0;
c=0;
bar_23=0;
bar=0;
a=0;
A=0;
s=gamma(1+(7));
d=(t);
foo=bar;
r=100*(1);
q=atan(inf);
p=asin(1);
o=acos(0);
n=cos(pi);
m=log(e);
Repay=(foo+tau_mathrmbar)/((Loans+t));
catching=exp((Loans+t-(foo+tau_mathrmbar))*(b));
l=((((((t)<=(Repay)))>=0.5 || ((0<(t)))>=0.5))<0.5)+(((0<(t)))>=0.5)+(((0<(t)))>=0.5);
k=(((0<(t)))>=0.5 && ((0<=(t)))>=0.5)+0+0;
g=(abs(t))*(frac(t))*(floor(t))*(((t)<0))*((0<(t)))*(((t)<(Repay)))*(((t)<=0))*((0<=(t)))*(((t)<=(Repay)));
h=((t)==0)+(0==(t))+((g)==(t));
i=min(g,t);
j=max(g,t)+max(t,0)+min(t,0)+min(0,t)+max(0,t);
f(1)=(foo)*(t);
f(2)=A+Repay-(catching);
f(3)=Repay-(catching);
f(4)=(a+b)^(log(c)/log(d));
f(5)=tanh(cosh(sinh(tan(cos(sin(log(sqrt(t))))))));
f(6)=atan(acos(asin(t)));
endfunction;

x0(1)=0;
x0(2)=0;
x0(3)=-0;
x0(4)=0;
x0(5)=0;
x0(6)=0;
