ARG version=22.04
FROM ubuntu:$version
ARG project=minsky
ARG version
ADD . /root
RUN cat /etc/os-release
RUN apt-get update -qq -y
RUN apt-get install -y gnupg2 curl
RUN curl -fsSL https://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_25.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/home_hpcoder1.gpg > /dev/null
RUN echo "deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_${version}/ /" >/etc/apt/sources.list.d/hpcoders.list
RUN apt-get update -qq -y
RUN apt-get install -y --allow-unauthenticated $project
RUN useradd -m minsky
# Get Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
#RUN su - minsky -c "minsky --version  --no-sandbox"
RUN python3 -c "import pyminsky"
