ARG version=22.04
FROM ubuntu:$version
ARG project=minsky
ARG version
ADD . /root
RUN cat /etc/os-release
RUN apt-get update -qq -y
RUN apt-get install -y wget gnupg2
RUN wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_${version}/Release.key
RUN apt-key add - < Release.key
RUN echo "deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_${version}/ /" >/etc/apt/sources.list.d/hpcoders.list
RUN apt-get update -qq -y
RUN apt-get install -y --allow-unauthenticated $project
RUN useradd -m minsky
#RUN su - minsky -c "minsky --version  --no-sandbox"
#RUN python3 -c "import pyminsky"
