FROM fedora:rawhide
ARG project=minsky
ADD . /root
#RUN dnf install -y --allowerasing 'dnf-command(config-manager)' util-linux
RUN yum install -y yum-utils
RUN yum-config-manager --add-repo https://download.opensuse.org/repositories/home:hpcoder1/Fedora_Rawhide/home:hpcoder1.repo
RUN yum install -y sudo $project --nogpgcheck
RUN useradd -m minsky
RUN chmod 4755 /usr/lib/minsky/chrome-sandbox
RUN sudo -u minsky minsky --version
RUN python3 -c "import pyminsky"
