FROM opensuse/leap:15.4
ARG project=minsky
ADD . /root
RUN zypper addrepo https://download.opensuse.org/repositories/home:hpcoder1/15.4/home:hpcoder1.repo
RUN zypper --gpg-auto-import-keys refresh
RUN zypper --non-interactive install $project
RUN useradd -m minsky
RUN su - minsky -c minsky --version
