FROM opensuse/tumbleweed
ARG project=minsky
ADD . /root
RUN zypper addrepo https://download.opensuse.org/repositories/home:hpcoder1/openSUSE_Tumbleweed/home:hpcoder1.repo
RUN zypper --gpg-auto-import-keys refresh
RUN zypper --non-interactive install $project python3
RUN useradd -m minsky
RUN su - minsky -c minsky --version
RUN python3 -c "import pyminsky"
